### PR TITLE
removed references to TranslationCredit [COM-763]

### PR DESCRIPTION
**Pull request by pbx**

### CODE REVIEW

**Comment by pbx** [comment]
I did some trailing-whitespace cleanup too, so if you can't figure out what changed in a line, that's probably it.

**Comment by pbx** [comment]
Oops, didn't mean to close, just meant to comment :\

**Comment by pbx** [comment]
I did some trailing-whitespace cleanup, so if you can't figure out what changed on some line that's probably it.

**Comment by lionbridge** [comment]
Rejecting this PR because nothing should change in the API

**Comment by pbx** [comment]
Would this be acceptable if `<TranslationCredit>0</TranslationCredit>` was added back to the examples where that element was removed?

**Comment by lionbridge** [comment]
I think we can solve this problem by not making any changes to the API documentation.  Nothing should change with that ticket.


Seth Gottlieb
VP, Product Development
Lionbridge
www.lionbridge.com | seth.gottlieb@lionbridge.com | 978.964.1923
________________________________

**Pull request closed without merging**
